### ISSUE TITLE
Can't Access All JWT Properties

### ISSUE THREAD

**Issue by colinmleslie** [FusionAuth/fusionauth-netcore-client#15]
When working with the ClientResponse<ValidateResponse> returned from the ValidateJWTAsync function, you cannot access all properties, as some are in the Non-Public members section under a variable called "otherClaims". For example, you cannot access the "roles" array. see image below for layout of successResponse property at time of issue discovery. In this case, otherClaims[3] contains the roles.

![image](https://user-images.githubusercontent.com/36854287/77466987-85517a00-6de1-11ea-8297-8254964be0f2.png)

**Comment by robotdan** [comment]
@tyduptyler13 can you take a look - is this perhaps from our Java 2 JSON mapping for the JWT class? 

I thinks this is the CS version of the Jackson `@AnySetter`

```
    public object this[string claim] {
      get => otherClaims[claim];
      set => otherClaims[claim] = value;
    }

    [JsonExtensionData]
    private readonly Dictionary<string, object> otherClaims = new Dictionary<string, object>();

```

Do we need to make that map public, or provide an accessor? 
https://github.com/FusionAuth/fusionauth-netcore-client/blob/master/fusionauth-netcore-client/domain/io/fusionauth/jwt/domain/JWT.cs

**Comment by tyduptyler13** [comment]
On it

**Comment by tyduptyler13** [comment]
Ok,

looking at the code and storage you can extract any value in the otherClaims by using the element acessor operator.

Example:
```c#
Assert.AreEqual(jwt["0"], new[] {"role 1"});
Assert.AreEqual(jwt["1"], "Test");
Assert.AreEqual(jwt["2"], 2);
Assert.AreEqual(jwt["3"], new[] {
  "a",
  "list",
  "of",
  "roles"
});
```

I will however change the return type for the future to return `dynamic` instead of `object`. I feel like dynamic would be a better "type" to use here to make the code a bit easier to deal with and make it so you don't have to do casting or keep your code super generic.

Do you have any objects to that change or how you access other claims?

**Comment by colinmleslie** [comment]
That sounds good to me! Thank you

**Comment by robotdan** [comment]
Client version 1.15.6  is available which should include the changes @tyduptyler13 made.
