### ISSUE TITLE
The "global" parameter does not work when logging out

### ISSUE THREAD

**Issue by EPRenaud** [FusionAuth/fusionauth-netcore-client#26]
Howdy 👋 

When I try to logout a user with the logout method, I receive an HTTP 400 error when I pass the `global` parameter.

**This code returns an HTTP 200 as expected**
```csharp
await _client.LogoutAsync(null, token);
```

**This code returns an HTTP 400**
```csharp
await _client.LogoutAsync(true, token);
```
The details of the error is 
```
message: Invalid
code: [couldNotConvert]global
```

**Comment by EPRenaud** [comment]
Hi @mooreds, sorry for the delay. 
`await _client.LogoutAsync(false, token);` gives me an HTTP 400 as well.

**Comment by epbensimpson** [comment]
I think I know the cause of this. Because `global` is `bool?`, the call to `withParameter` is using the overload that takes `object` rather than the `bool` one. 

https://github.com/FusionAuth/fusionauth-netcore-client/blob/f2d64876045d9ebe55bef344fc01449fe30bd291/fusionauth-netcore-client/src/io/fusionauth/IRESTClient.cs#L98-L104

The output of `bool.ToString()` is `True` or `False` rather than `true` or `false`, and presumably the server is expecting the latter.

**Comment by EPRenaud** [comment]
Thanks @epbensimpson, I created a PR to fix this 😉
